config/routes.rb
Rails.application.routes.draw do

  root 'static#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  resources :users, only: [:show, :index] do
    resources :planets, only: [:show]
    get 'destroy-planets' => 'planets#destroy_all'
  end

  resources :planets do
    resources :orders, only: [:new]
  end

  resources :orders, only: [:index, :show, :new, :create]

  resources :features, only: [:index, :show, :create] do
    resources :orders, only: [:index]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :planets

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.first_name
    end      
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def features_total
    array = []
    self.planets.each do |planet|
      planet.orders.each do |order|
        array << order.price * 1000
      end
    end
    array.inject(0){|sum,x| sum + x }
  end

  def planets_total
    self.planets.sum(:price) * 1000
  end

  def total_spent
    self.features_total + self.planets_total
  end

  def self.most_valued
    array = []
    all.each do |user|
      array << { user: user, total_spent: user.features_total + user.planets_total }
    end
    array.sort_by { |hash| hash[:total_spent] }.last
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
	  sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		if user_signed_in?
			@user = User.find(params[:id])
      render :show
    else
      flash[:alert] = "You must be logged in to view profiles."
      redirect_to root_path
    end
  end

end

app/views/users/index.html.erb
<h1>Customer List</h1>

<table class="table">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Email</th>
		<th>Number of Planets</th>
	</tr>
	<% @users.each do |user| %>
		<tr>
			<td><%= user.id %></td>
			<td><%= link_to user.name.titleize, user_path(user) %></td>
			<td><%= user.email %></td>
			<td><%= user.planets.count %></td>
		</tr>
	<% end %>
</table>

app/views/users/show.html.erb
<div class="jumbotron">
	<h1><%= @user.name.titleize %></h1>
	<h2>Number of planets: <%= @user.planets.count %></h2>
	<h3>Total amount spent on planets: <%= @user.planets_total %> Pu</h3>
	<h3>Total amount spent on features: <%= @user.features_total %> Pu</h3>
	<h2>Total amount spent: <%= @user.total_spent %> Pu</h2>
</div>

<table class="table">
	<tr>
		<th>Planets</th>
		<th>Number of Features</th>
		<th>Amount Spent on Features</th>
		<th></th>
		<th></th>
	</tr>
	<% @user.planets.each do |planet| %>
		<tr>
			<td><%= link_to planet.name, user_planet_path(@user, planet) %></td>
			<td><%= planet.features.count %></td>
			<td><%= planet.orders.sum(:price) * 1000 %></td>
			<% if planet.user == current_user %>
				<td><%= link_to 'Edit', edit_planet_path(planet) %></td>
				<td><%= link_to 'Destroy', planet, method: :delete, data: { confirm: 'Are you sure?'} %></td>
			<% end %>
		</tr>
	<% end %>
</table>

<% if @user == current_user %>
	<%= link_to "End the Universe", user_destroy_planets_path(@user), data: { confirm: 'Are you sure?'} %>
<% end %>