config/routes.rb
Rails.application.routes.draw do

  root 'static#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  resources :users, only: [:show, :index] do
    resources :planets, only: [:show]
    get 'destroy-planets' => 'planets#destroy_all'
  end

  resources :planets do
    resources :orders, only: [:new]
  end

  resources :orders, only: [:index, :show, :new, :create]

  resources :features, only: [:index, :show, :create] do
    resources :orders, only: [:index]
  end

end

app/models/planet.rb
class Planet < ActiveRecord::Base
	before_save { self.name = name.titleize }

	belongs_to :user
	has_many :orders
	has_many :features, through: :orders

	validates :name, presence: true, uniqueness: true, length: { in: 3..20 }
	validates :moons, numericality: { less_than_or_equal_to: 15 }
	validates :population, numericality: { less_than_or_equal_to: 8000000 }

	def self.most_populated
		order('population desc').first
	end

	def self.most_moons
		order('moons desc').first
	end

	def self.most_expensive
		order('price desc').first
	end

	def orders_attributes=(attributes)
		attributes.values.each do |att|
			if !att[:feature_id].blank? || !att[:feature_attributes].blank? && !att[:size].blank?
				order = Order.new(att)
				order.planet = self
				order.price = rand(1000..8000)
				self.orders << order
			end
		end
	end

end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :find_planet, except: [:index, :show, :new, :create, :destroy_all]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @planets = Planet.all
    @most_valued = User.most_valued
    @most_valued_customer = @most_valued[:user]
    @most_populated = Planet.most_populated
    @most_moons = Planet.most_moons
    @most_expensive = Planet.most_expensive
  end

  def show
    if params[:user_id]
      @planet = Planet.find(params[:id])
    else
      @planet = Planet.find(params[:id])
    end
  end

  def new
    @planet = Planet.new
    @orders = @planet.orders.build
    @feature = @orders.build_feature
  end

  def create
    binding.pry
    @planet = Planet.new(planet_params)
    @planet.price = rand(1000000..8000000)
    @planet.user = current_user
    if !@planet.valid? || !user_signed_in?
      flash[:alert] = "Please make sure you have entered in the correct information."
      redirect_to new_planet_path
    else
      @planet.save
      flash[:notice] = "Your new planet #{@planet.name.titleize} and features cost a total of #{@planet.price * 1000 + @planet.orders.sum(:price) * 1000} Pu. We have deducted this amount from your account. Thank you for your business."
      redirect_to planet_path(@planet)
    end
  end

  def edit
    if @planet.user == current_user
      render :edit
    else
      flash[:alert] = "You cannot edit another user's planets."
      redirect_to planets_path
    end
  end

  def update
    if @planet.user == current_user && @planet.update(planet_params)
      redirect_to planet_path(@planet)
    else
      flash[:alert] = "You cannot edit another user's planets."
      redirect_to planets_path
    end
  end

  def destroy
    @user = @planet.user
    if @planet.user == current_user
      @planet.destroy
    else
      flash[:alert] = "You cannot destroy another user's planets."
    end
    redirect_to user_path(@user)
  end

  def destroy_all
    if current_user.planets.count == 0
      flash[:alert] = "You don't have any planets to destroy."
    elsif params[:user_id].to_i == current_user.id
      current_user.planets.destroy_all
      flash[:notice] = "The universe has successfully ended. Please purchase new planets to start over."
    else
      flash[:alert] = "You must be the owner to destroy the planets."
    end
    redirect_to user_path(current_user)
  end

  private

  def planet_params
    params.require(:planet).permit(:id, :name, :price, :population, :moons, orders_attributes: [:id, :size, :feature_id, feature_attributes: [:id, :name, :description]])
  end

  def find_planet
    @planet = Planet.find(params[:id])
  end

end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/planets/edit.html.erb
<h1>Edit Planet</h1>

<%= form_for @planet do |f| %>

  <% if @planet.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@planet.errors.count, "error") %>
        prohibited this form from being submitted:
      </h3>

      <ul>
      <% @planet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<% f.hidden_field :price %>

	<div class="form-group">
		<%= f.label :name %> (between 3-20 letters)
    <%= f.text_field :name, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :population %> (in thousands, max. 8,000,000,000)
    <%= f.number_field :population, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :moons %> (max. 15)
    <%= f.number_field :moons, class: "form-control" %>
	</div>

	<%= f.submit 'Submit', class: "btn btn-default" %>

<% end %>

app/views/planets/index.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="jumbotron">
			<h4>Most Valued Customer Award:</h4>
			<p class="lead"><%= link_to @most_valued_customer.name, user_path(@most_valued_customer) %></p>
			<p>Total Spent: <%= @most_valued[:total_spent] %> Pu</p>
		</div>

		<div class="jumbotron">
			<h4>Most Populated Planet Award:</h4>
			<p class="lead"><%= link_to @most_populated.name.titleize, planet_path(@most_populated) %></p>
			<p>Population: <%= @most_populated.population * 1000 %></p>
			<p>Owner: <%= link_to @most_populated.user.name.titleize, user_path(@most_populated.user) %></p>
		</div>

		<div class="jumbotron">
			<h4>Most Moons Planet Award:</h4>
			<p class="lead"><%= link_to @most_moons.name.titleize, planet_path(@most_moons) %></p>
			<p>Moons: <%= @most_moons.moons %></p>
			<p>Owner: <%= link_to @most_moons.user.name.titleize, user_path(@most_moons.user) %></p>
		</div>

		<div class="jumbotron">
			<h4>Most Expensive Planet Award:</h4>
			<p class="lead"><%= link_to @most_expensive.name.titleize, planet_path(@most_expensive) %></p>
			<p>Price: <%= @most_expensive.price * 1000 %> Pu</p>
			<p>Owner: <%= link_to @most_expensive.user.name.titleize, user_path(@most_expensive.user) %></p>
		</div>
	</div>
	<div class="col-md-6">
		<table class="table">
			<tr>
				<th>Planet</th>
				<th>Owner</th>
				<th>Price (Pu) </th>
			</tr>
			<% @planets.each do |planet| %>
				<tr>
					<td><%= link_to planet.name.titleize, planet_path(planet) %></td>
					<td><%= link_to planet.user.name.titleize, user_path(planet.user) %></td>
					<td><%= planet.price * 1000 %></td>
				</tr>
			<% end %>	
		</table>
	</div>
</div>

app/views/planets/new.html.erb
<h1>Order A New Planet</h1>

<%= form_for @planet do |f| %>

  <% if @planet.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@planet.errors.count, "error") %>
        prohibited this form from being submitted:
      </h3>

      <ul>
      <% @planet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<% f.hidden_field :price %>

	<div class="form-group">
		<%= f.label :name %> (between 3-20 letters)
    <%= f.text_field :name, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :population %> (in thousands, max. 8,000,000,000)
    <%= f.number_field :population, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :moons %> (max. 15)
    <%= f.number_field :moons, class: "form-control" %>
	</div>

	<h2>Choose Features (Optional)</h2>

	<h3>Feature 1</h3>
	<div class="form-group">
		<%= f.fields_for :orders do |ff| %>

			<%= ff.collection_select :feature_id, Feature.all, :id, :name, {:prompt => 'Select'} %>

		  <%= ff.label :size %> (in fy sq., max. 8,000,000)
		  <%= ff.number_field :size %>

    <% end %>
	</div>

	<h3>Feature 2</h3>
	<div class="form-group">
		<%= f.fields_for :orders do |ff| %>

			<%= ff.collection_select :feature_id, Feature.all, :id, :name, {:prompt => 'Select'} %>

		  <%= ff.label :size %> (in fy sq., max. 8,000,000)
		  <%= ff.number_field :size %>

    <% end %>
	</div>

	<h3>Feature 3</h3>
	<div class="form-group">
		<%= f.fields_for :orders do |ff| %>

			<%= ff.collection_select :feature_id, Feature.all, :id, :name, {:prompt => 'Select'}, {:prompt => 'Select'} %>

		  <%= ff.label :size %> (in fy sq., max. 8,000,000)
		  <%= ff.number_field :size %>

    <% end %>
	</div>

	<h3>Custom Feature</h3>

	<div class="form-group">
		<%= f.fields_for :orders do |ff| %>

	    <%= ff.fields_for :feature do |fff| %>

	      <%= fff.label :name %>
	      <%= fff.text_field :name, class: "form-control" %>

	      <%= fff.label :description %>
	      <%= fff.text_area :description, class: "form-control" %>
	    <% end %>

		  <%= ff.label :size %> (in fy sq., max. 8,000,000)
		  <%= ff.number_field :size, class: "form-control" %>

    <% end %>
	</div>

	<%= f.submit 'Order Planet', class: "btn btn-default" %>

<% end %>

app/views/planets/show.html.erb
<div class="jumbotron">
	<h1>Welcome to <%= @planet.name.titleize %></h1>

	<ul class="list-group">
		<li class="list-group-item">Owner: <%= link_to @planet.user.name.titleize, user_path(@planet.user) %></li>
		<li class="list-group-item">Population: <%= @planet.population * 1000 %></li>
		<li class="list-group-item">Moons: <%= @planet.moons %></li>
		<li class="list-group-item">Price: <%= @planet.price * 1000 %> Pu</li>
		<li class="list-group-item">Number of Features: <%= @planet.features.count %></li>
	</ul>
</div>

<h2>Features:</h2>
<table class="table">
	<tr>
		<th>Feature</th>
		<th>Size (fy sq.)</th>
		<th>Price (Pu)</th>
	</tr>
	<% @planet.orders.each do |order| %>
		<tr>
			<td><%= link_to order.feature.name.titleize, feature_path(order.feature) %></td>
			<td><%= order.size %></td>
			<td><%= order.price * 1000 %></td>
		</tr>
	<% end %>
</table>

<button class="btn btn-default"><%= link_to 'Add New Feature', new_order_path %></button>