config/routes.rb
Rails.application.routes.draw do

  root 'static#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  resources :users, only: [:show, :index] do
    resources :planets, only: [:show]
    get 'destroy-planets' => 'planets#destroy_all'
  end

  resources :planets do
    resources :orders, only: [:new]
  end

  resources :orders, only: [:index, :show, :new, :create]

  resources :features, only: [:index, :show, :create] do
    resources :orders, only: [:index]
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :planet
	belongs_to :feature

	validates :size, presence: true, numericality: { less_than_or_equal_to: 8000000 }

	def feature_attributes=(attributes)
		feature = Feature.find_or_create_by(attributes)
		self.feature_id = feature.id
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, except: [:index, :new, :create]
  before_action :set_feature, except: [:new]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @orders = @feature.orders
    # @orders = Order.all

    render json: @orders
  end

  def show
  end

  def new
    @order = Order.new
    # before_action :set_feature caused error:
      # Couldn't find Feature with 'id'=
      # changed as follows: 
        # before_action :set_feature
        # before_action :set_feature, except: [:new]
  end

  def create
    @order = Order.new(order_params)
    @order.price = rand(1000..8000)
    if !@order.valid? || @order.feature_id.nil? || @order.feature_id.blank? || @order.planet_id.blank?
      flash[:alert] = "Please make sure you have entered in the correct information."
      redirect_to new_ord er_path
    else
      @order.save
      flash[:notice] = "Your new #{@order.feature.name.downcase} for #{@order.planet.name.titleize} costs #{@order.price * 1000} Pu. We have deducted this amount from your account. Thank you for your business."
      redirect_to user_path(@order.planet.user)
    end
  end

  private

  def order_params
    params.require(:order).permit(:id, :price, :size, :feature_id, :planet_id, feature_attributes: [:id, :name, :description])
  end

  def find_order
    @order = Order.find(params[:id])
  end

  def set_feature
    @feature = Feature.find(params[:feature_id])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<table class="table">
	<tr>
		<th>Order ID</th>
		<th>Feature</th>
		<th>Planet</th>
		<th>Size (fy sq.)</th>
		<th>Price (Pu)</th>
		<th>Customer</th>
		<th>Customer Email</th>
	</tr>
	<% @orders.each do |order| %>
		<tr>
			<td><%= order.id %></td>
			<td><%= order.feature.name %></td>
			<td><%= link_to order.planet.name, planet_path(order.planet) %></td>
			<td><%= order.size %></td>
			<td><%= order.price * 1000 %></td>
			<td><%= link_to order.planet.user.name, user_path(order.planet.user) %></td>
			<td><%= order.planet.user.email %></td>
		</tr>
	<% end %>
</table>

app/views/orders/new.html.erb
<div class="row">
	<div class="jumbotron col-md-6">
		<h2>Order A Feature</h2>
		
		<%= form_for @order do |f| %>
			<% if @order.errors.any? %>
		    <div id="error_explanation">
		      <h3>
		        <%= pluralize(@order.errors.count, "error") %>
		        prohibited this form from being submitted:
		      </h3>

		      <ul>
		      <% @order.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		
			<% f.hidden_field :price %>
		
			<div class="form-group">
				<h3><%= f.label 'Choose a Planet' %></h3>
		    <%= f.collection_select :planet_id, current_user.planets, :id, :name, {:prompt => 'Select'}, :class => "form-control" %>
			</div>
		
			<div class="form-group">
				<%= f.fields_for :feature, Feature.new do |ff| %>
					<h3><%= f.label 'Choose a feature', class: "form-check-inline" %></h3>
			    <%= f.collection_select :feature_id, Feature.all, :id, :name, {:prompt => 'Select'}, class: "form-control" %>
			  <% end %>

			  <%= f.label :size, class: "form-check-inline" %> (in fy sq., max. 8,000,000)
		    <%= f.number_field :size, class: "form-control" %>
			</div>
		
			<%= f.submit 'Order Feature', class: "btn btn-default" %>
		
		<% end %>
	</div>
	
	<div class="jumbotron col-md-6">
		<h2>Or Create A Custom Feature</h2>
		
		<%= form_for @order do |f| %>
		
			<% f.hidden_field :price %>
		
			<div class="form-group">
				<h3><%= f.label 'Choose a Planet' %></h3>
		    <%= f.collection_select :planet_id, current_user.planets, :id, :name, {:prompt => 'Select'}, :class => "form-control" %>
			</div>
		
			<div class="form-group">
		    <%= f.fields_for :feature, Feature.new do |ff| %>
		
		      <%= ff.label 'New Feature Name' %>
		      <%= ff.text_field :name, class: "form-control" %>
		
		      <%= ff.label :description %>
		      <%= ff.text_area :description, class: "form-control" %>
		    <% end %>
		
		    <%= f.label :size %> (in fy sq., max. 8,000,000)
		    <%= f.number_field :size, class: "form-control" %>
			</div>
		
			<%= f.submit 'Order Feature', class: "btn btn-default" %>
		
		<% end %>
	</div>
</div>