config/routes.rb
Rails.application.routes.draw do

  root 'static#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  resources :users, only: [:show, :index] do
    resources :planets, only: [:show]
    get 'destroy-planets' => 'planets#destroy_all'
  end

  resources :planets do
    resources :orders, only: [:new]
  end

  resources :orders, only: [:index, :show, :new, :create]

  resources :features, only: [:index, :show, :create] do
    resources :orders, only: [:index]
  end

end

app/views/layouts/_messages.html.erb
<% if notice || alert %>
  <div class="alert <%= notice ? "alert-info" : "" %><%= alert ? "alert-danger" : "" %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <div>
      <% if notice %>
        <%= notice %>
      <% elsif alert %>
        <%= alert %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar">
	<% if current_user %>
		<div class="text-right">
			<p>Hi, <%= current_user.name.titleize %></p>
			<%= link_to("Sign out", destroy_user_session_path, :method => "delete") %> | 
			<%= link_to "My Profile", user_path(current_user) %>
		</div>

		<div class="text-left">
			<%= link_to 'Home', root_path %> | 
			<%= link_to 'Browse Planets', planets_path %> | 
			<%= link_to 'Browse Features', features_path %> | 
			<%= link_to 'Order Planet', new_planet_path %> | 
			<%= link_to 'Order Feature', new_order_path %>
		</div>
	<% else %>
		<div class="text-right">
			<%= link_to("Sign in", new_user_session_path) %> | 
			<%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %> | 
			<%= link_to("Sign up", new_user_registration_path) %>
		</div>

		<div class="text-left">
			<%= link_to 'Home', root_path %> | 
			<%= link_to 'Browse Planets', planets_path %> | 
			<%= link_to 'Browse Features', features_path %>
		</div>
		
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OovartsPlanetShop</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<h1 class="logo">
		<a href="/">Oovart's Planet Shop at the End of the Universe</a>
	</h1>

  <%= render 'layouts/messages' %>
  <%= render 'layouts/navigation' %>

	<%= yield %>
</div>

</body>
</html>